import re
import sys
import os

def merge_toon_to_code_v3(toon_path, target_code_path):
    if not os.path.exists(toon_path):
        return f"Error: TOON file not found at {toon_path}"

    with open(toon_path, 'r', encoding='utf-8') as f:
        toon_content = f.read()

    if os.path.exists(target_code_path):
        with open(target_code_path, 'r', encoding='utf-8') as f:
            code = f.read()
    else:
        code = ""

    # --- 1. Client Directive & Imports ---
    if "client:true" in toon_content and '"use client"' not in code:
        code = '"use client";\n\n' + code

    import_section_match = re.search(r'imports:\n((?:\s+-\s+.*\n?)*)', toon_content)
    if import_section_match:
        import_lines = import_section_match.group(1).strip().split('\n')
        for line in import_lines:
            line = line.strip()
            if line.startswith('- '):
                match = re.match(r'-\s+(.+?):\s+\[(.*?)\]', line)
                if match:
                    path = match.group(1)
                    items = match.group(2)
                    if f'from "{path}"' not in code and f"from '{path}'" not in code:
                        code = f'import {{ {items} }} from "{path}";\n' + code

    # --- 2. Component/Hook Wrapper ---
    comp_match = re.search(r'(?:component|hook):(\w+)', toon_content)
    comp_name = comp_match.group(1) if comp_match else "UnknownComponent"
    
    # --- 【新規】3. Types / Interfaces の復元 ---
    types_match = re.search(r'types:\n((?:\s+-\s+.*\n?)*)', toon_content)
    types_code = ""
    if types_match:
        type_lines = types_match.group(1).strip().split('\n')
        for line in type_lines:
            line = line.strip()
            if line.startswith('- '):
                type_def = line[2:] # 例: interface NavHeaderProps { ... }
                name_match = re.match(r'(?:interface|type)\s+(\w+)', type_def)
                if name_match:
                    t_name = name_match.group(1)
                    # 既存のコードに型定義が存在しない場合のみ追加
                    if f"interface {t_name}" not in code and f"type {t_name}" not in code:
                        types_code += f"export {type_def}\n\n"
                        
    # コンポーネントの定義がない場合は外枠を作る
    if f"export function {comp_name}" not in code:
        code += f"{types_code}\nexport function {comp_name}() {{\n  // Generated by TOON\n\n  return null;\n}}"
    elif types_code:
        # 既存コードの import 文とコンポーネント定義の間に型定義を挿入
        comp_index = code.find(f"export function {comp_name}")
        if comp_index != -1:
            code = code[:comp_index] + types_code + code[comp_index:]

    # --- 4. Logic (State & Hooks) の復元 ---
    logic_section = re.search(r'logic:(.*?)(?=\n\w+:|$)', toon_content, re.DOTALL)
    if logic_section:
        hooks = re.findall(r'(\w+)\((.*?)\)\s*->\s*\[(.*?)\]', logic_section.group(1))
        for h_name, h_args, h_vars in hooks:
            h_vars = h_vars.strip()
            if h_vars not in code:
                insertion_point = code.find(f"export function {comp_name}")
                if insertion_point != -1:
                    # 'export function Name(...) {' の後ろを探す
                    bracket_point = code.find('{', insertion_point) + 1
                    new_line = f"\n  const [{h_vars}] = {h_name}({h_args});" if "," in h_vars else f"\n  const {h_vars} = {h_name}({h_args});"
                    code = code[:bracket_point] + new_line + code[bracket_point:]

    # --- 5. Internal Logic / Flows (handleXXX) ---
    flows = re.findall(r'(\w+):\s*flow:(.*)', toon_content)
    for f_name, f_flow in flows:
        if f_name not in code:
            return_pos = code.rfind("return")
            if return_pos != -1:
                func_code = f"\n  const {f_name} = () => {{\n    // TOON Flow: {f_flow.strip()}\n  }};\n"
                code = code[:return_pos] + func_code + code[return_pos:]

    # --- 6. Returns の同期 ---
    return_match = re.search(r'returns:\[(.*?)\]', toon_content)
    if return_match:
        ret_vars = return_match.group(1).strip()
        code = re.sub(r'return\s+\{?.*?\}?;', f'return {{ {ret_vars} }};', code, flags=re.DOTALL)

    # --- 【微調整】7. Render Tree / JSX className の正確な順次マージ ---
    render_tree_match = re.search(r'render_tree:\n((?:\s+-\s+.*\n?)*)', toon_content)
    if render_tree_match and "return null;" not in code:
        render_lines = render_tree_match.group(1).strip().split('\n')
        
        # タグの出現回数をカウントする辞書 (例: {'Link': 2, 'li': 3})
        tag_counts = {}
        
        for line in render_lines:
            line = line.strip()
            if line.startswith('- '):
                element_def = line[2:]
                
                # タグ名と属性全体の抽出
                tag_match = re.match(r'([a-zA-Z0-9_]+)(?:\((.*)\))?', element_def)
                if tag_match:
                    tag_name = tag_match.group(1)
                    attrs_str = tag_match.group(2) or ""
                    
                    # このタグ名が登場した回数をインクリメント
                    tag_counts[tag_name] = tag_counts.get(tag_name, 0) + 1
                    n_th_occurrence = tag_counts[tag_name]
                    
                    # TOON側に className の指定がある場合のみ更新処理を行う
                    class_match = re.search(r'className:"([^"]*)"', attrs_str)
                    if class_match:
                        new_class = class_match.group(1)
                        tag_pattern = re.compile(rf'(<\s*{tag_name}\b)([^>]*?)(/?>)', re.DOTALL)
                        
                        def update_tag(m):
                            tag_start = m.group(1)
                            attrs = m.group(2) or ""
                            tag_end = m.group(3)
                            
                            if 'className=' in attrs:
                                attrs = re.sub(r'className\s*=\s*"[^"]*"', f'className="{new_class}"', attrs)
                                attrs = re.sub(r"className\s*=\s*'[^']*'", f'className="{new_class}"', attrs)
                            else:
                                attrs = f' className="{new_class}"' + attrs
                            return tag_start + attrs + tag_end

                        # N番目のマッチ要素だけを正確に置換する
                        matches = list(tag_pattern.finditer(code))
                        if len(matches) >= n_th_occurrence:
                            m = matches[n_th_occurrence - 1]
                            code = code[:m.start()] + update_tag(m) + code[m.end():]

    with open(target_code_path, 'w', encoding='utf-8') as f:
        f.write(code)
    
    return f"Successfully restored/merged TOON into {target_code_path}"

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python toon2code.py <input.toon> <target.ts>")
    else:
        result = merge_toon_to_code_v3(sys.argv[1], sys.argv[2])
        print(result)
