import re
import sys
import os

def merge_toon_to_code_v3(toon_path, target_code_path):
    """
    TOON形式の設計図に基づき、TypeScript/Reactコードを精密に復元・更新する
    """
    if not os.path.exists(toon_path):
        return f"Error: TOON file not found at {toon_path}"

    with open(toon_path, 'r', encoding='utf-8') as f:
        toon_content = f.read()

    # 既存ファイルがあれば読み込み、なければ新規作成の雛形を準備
    if os.path.exists(target_code_path):
        with open(target_code_path, 'r', encoding='utf-8') as f:
            code = f.read()
    else:
        code = ""

    # --- 1. Client Directive & Imports ---
    if "client:true" in toon_content and '"use client"' not in code:
        code = '"use client";\n\n' + code

    import_match = re.search(r'imports:\[(.*?)\]', toon_content)
    if import_match:
        new_imports = [imp.strip() for imp in import_match.group(1).split(',')]
        for imp in new_imports:
            if imp and f"from" not in code and imp not in code:
                # 汎用的なインポート文の挿入（必要に応じてパスを調整）
                if imp in ["useState", "useEffect", "useRef", "useCallback"]:
                    if 'import { ' + imp not in code:
                        code = f"import {{ {imp} }} from 'react';\n" + code
                else:
                    code = f"import {{ {imp} }} from './{imp}';\n" + code

    # --- 2. Component/Hook Wrapper ---
    comp_match = re.search(r'(?:component|hook):(\w+)', toon_content)
    comp_name = comp_match.group(1) if comp_match else "UnknownComponent"
    
    if f"export function {comp_name}" not in code:
        code += f"\nexport function {comp_name}() {{\n  // Generated by TOON\n\n  return null;\n}}"

    # --- 3. Logic (State & Hooks) の復元 ---
    # logic セクションの内容を抽出
    logic_section = re.search(r'logic:(.*?)(?=\n\w+:|$)', toon_content, re.DOTALL)
    if logic_section:
        # TOONの logic 行 (例: useState(false) -> [menuOpen,setMenuOpen]) を抽出
        hooks = re.findall(r'(\w+)\((.*?)\)\s*->\s*\[(.*?)\]', logic_section.group(1))
        
        for h_name, h_args, h_vars in hooks:
            h_vars = h_vars.strip()
            # 既に定義されていないかチェック
            if h_vars not in code:
                # 関数開始直後に挿入
                insertion_point = code.find(f"export function {comp_name}() {{") + len(f"export function {comp_name}() {{")
                
                # 配列・オブジェクトデストラクトの判定
                if "," in h_vars:
                    new_line = f"\n  const [{h_vars}] = {h_name}({h_args});"
                else:
                    new_line = f"\n  const {h_vars} = {h_name}({h_args});"
                
                code = code[:insertion_point] + new_line + code[insertion_point:]

    # --- 4. Internal Logic / Flows (handleXXX) ---
    # flows: セクションがある場合、それらを関数として挿入
    flows = re.findall(r'(\w+):\s*flow:(.*)', toon_content)
    for f_name, f_flow in flows:
        if f_name not in code:
            # return 文の手前に挿入
            return_pos = code.rfind("return")
            func_code = f"\n  const {f_name} = () => {{\n    // TOON Flow: {f_flow.strip()}\n  }};\n"
            code = code[:return_pos] + func_code + code[return_pos:]

    # --- 5. Returns の同期 ---
    return_match = re.search(r'returns:\[(.*?)\]', toon_content)
    if return_match:
        ret_vars = return_match.group(1).strip()
        # return 文を TOON の定義に合わせて置換
        code = re.sub(r'return\s+\{?.*?\}?;', f'return {{ {ret_vars} }};', code, flags=re.DOTALL)

    # --- 6. 【新規追加】 Render Tree / JSX className の復元・マージ ---
    render_tree_match = re.search(r'render_tree:\n((?:\s+-\s+.*\n?)*)', toon_content)
    if render_tree_match:
        render_lines = render_tree_match.group(1).strip().split('\n')
        
        # パターンA: 新規生成時（JSXがまだない場合） -> 雛形を組む
        if "return null;" in code:
            jsx_elements = []
            for line in render_lines:
                line = line.strip()
                if line.startswith('- '):
                    element_def = line[2:]
                    tag_match = re.match(r'([a-zA-Z0-9_]+)(?:\(className:"([^"]*)"\))?', element_def)
                    if tag_match:
                        tag_name = tag_match.group(1)
                        class_val = tag_match.group(2)
                        
                        attr_str = f' className="{class_val}"' if class_val else ""
                        if tag_name[0].isupper():
                            # カスタムコンポーネント (自己修了タグ)
                            jsx_elements.append(f'      <{tag_name}{attr_str} />')
                        else:
                            # 標準HTMLタグ
                            jsx_elements.append(f'      <{tag_name}{attr_str}></{tag_name}>')
            
            jsx_string = "return (\n    <>\n" + "\n".join(jsx_elements) + "\n    </>\n  );"
            code = code.replace("return null;", jsx_string)
            
        # パターンB: 既存ファイルへのマージ -> クラス名を上書き/追記
        else:
            for line in render_lines:
                line = line.strip()
                if line.startswith('- '):
                    element_def = line[2:]
                    # TOONからクラス名を持つ要素のみを抽出
                    tag_match = re.match(r'([a-zA-Z0-9_]+)\(className:"([^"]*)"\)', element_def)
                    if tag_match:
                        tag_name = tag_match.group(1)
                        new_class = tag_match.group(2)
                        
                        # 該当するタグをソースコード内から正規表現で検索
                        # 例: <header ... > または <header>
                        tag_pattern = re.compile(rf'(<\s*{tag_name}\b)([^>]*?)(/?>)', re.DOTALL)
                        
                        def update_tag(m):
                            tag_start = m.group(1)
                            attrs = m.group(2) or ""
                            tag_end = m.group(3)
                            
                            # すでにclassNameが存在する場合は値を置換、無い場合は追加
                            if 'className=' in attrs:
                                # "..." 形式と '...' 形式の単純な文字列クラス名のみ置換
                                attrs = re.sub(r'className\s*=\s*"[^"]*"', f'className="{new_class}"', attrs)
                                attrs = re.sub(r"className\s*=\s*'[^']*'", f'className="{new_class}"', attrs)
                            else:
                                attrs = f' className="{new_class}"' + attrs
                                
                            return tag_start + attrs + tag_end

                        # 最初に見つかった該当タグのclassNameを更新
                        code = tag_pattern.sub(update_tag, code, count=1)

    # 修正結果の保存
    with open(target_code_path, 'w', encoding='utf-8') as f:
        f.write(code)
    
    return f"Successfully restored/merged TOON into {target_code_path}"

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python toon2code.py <input.toon> <target.ts>")
    else:
        result = merge_toon_to_code_v3(sys.argv[1], sys.argv[2])
        print(result)
