import re
import sys
import os

def merge_toon_to_code_v3(toon_path, target_code_path):
    """
    TOON形式の設計図に基づき、TypeScript/Reactコードを精密に復元・更新する
    """
    if not os.path.exists(toon_path):
        return f"Error: TOON file not found at {toon_path}"

    with open(toon_path, 'r', encoding='utf-8') as f:
        toon_content = f.read()

    # 既存ファイルがあれば読み込み、なければ新規作成の雛形を準備
    if os.path.exists(target_code_path):
        with open(target_code_path, 'r', encoding='utf-8') as f:
            code = f.read()
    else:
        code = ""

    # --- 1. Client Directive & Imports ---
    if "client:true" in toon_content and '"use client"' not in code:
        code = '"use client";\n\n' + code

    import_match = re.search(r'imports:\[(.*?)\]', toon_content)
    if import_match:
        new_imports = [imp.strip() for imp in import_match.group(1).split(',')]
        for imp in new_imports:
            if imp and f"from" not in code and imp not in code:
                # 汎用的なインポート文の挿入（必要に応じてパスを調整）
                if imp in ["useState", "useEffect", "useRef", "useCallback"]:
                    if 'import { ' + imp not in code:
                        code = f"import {{ {imp} }} from 'react';\n" + code
                else:
                    code = f"import {{ {imp} }} from './{imp}';\n" + code

    # --- 2. Component/Hook Wrapper ---
    comp_match = re.search(r'(?:component|hook):(\w+)', toon_content)
    comp_name = comp_match.group(1) if comp_match else "UnknownComponent"
    
    if f"export function {comp_name}" not in code:
        code += f"\nexport function {comp_name}() {{\n  // Generated by TOON\n\n  return null;\n}}"

    # --- 3. Logic (State & Hooks) の復元 ---
    # logic セクションの内容を抽出
    logic_section = re.search(r'logic:(.*?)(?=\n\w+:|$)', toon_content, re.DOTALL)
    if logic_section:
        # TOONの logic 行 (例: useState(false) -> [menuOpen,setMenuOpen]) を抽出
        hooks = re.findall(r'(\w+)\((.*?)\)\s*->\s*\[(.*?)\]', logic_section.group(1))
        
        for h_name, h_args, h_vars in hooks:
            h_vars = h_vars.strip()
            # 既に定義されていないかチェック
            if h_vars not in code:
                # 関数開始直後に挿入
                insertion_point = code.find(f"export function {comp_name}() {{") + len(f"export function {comp_name}() {{")
                
                # 配列・オブジェクトデストラクトの判定
                if "," in h_vars:
                    new_line = f"\n  const [{h_vars}] = {h_name}({h_args});"
                else:
                    new_line = f"\n  const {h_vars} = {h_name}({h_args});"
                
                code = code[:insertion_point] + new_line + code[insertion_point:]

    # --- 4. Internal Logic / Flows (handleXXX) ---
    # flows: セクションがある場合、それらを関数として挿入
    flows = re.findall(r'(\w+):\s*flow:(.*)', toon_content)
    for f_name, f_flow in flows:
        if f_name not in code:
            # return 文の手前に挿入
            return_pos = code.rfind("return")
            func_code = f"\n  const {f_name} = () => {{\n    // TOON Flow: {f_flow.strip()}\n  }};\n"
            code = code[:return_pos] + func_code + code[return_pos:]

    # --- 5. Returns の同期 ---
    return_match = re.search(r'returns:\[(.*?)\]', toon_content)
    if return_match:
        ret_vars = return_match.group(1).strip()
        # return 文を TOON の定義に合わせて置換
        code = re.sub(r'return\s+\{?.*?\}?;', f'return {{ {ret_vars} }};', code, flags=re.DOTALL)

    # 修正結果の保存
    with open(target_code_path, 'w', encoding='utf-8') as f:
        f.write(code)
    
    return f"Successfully restored/merged TOON into {target_code_path}"

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python toon2code.py <input.toon> <target.ts>")
    else:
        result = merge_toon_to_code_v3(sys.argv[1], sys.argv[2])
        print(result)
